language: rust
sudo: false
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

# run builds for both all the trains
rust:
  - nightly
  - beta
  - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="clippy"
notifications:
  email: false
