language: rust
sudo: false
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

# run builds for both all the trains
rust:
  - stable
  - beta
  - nightly

script:
  - cargo test

env:
  global:
    - RUST_BACKTRACE=1
notifications:
  email: false
